# Bots in Science ðŸ§ª

## Libraries

In [8]:
import pandas as pd
from functions import bot_mentions

## 1. Correspondings' country

In [14]:
ãƒ‡ãƒ¼ã‚¿_cy = pd.read_csv('data/papers_country.tsv', sep='\t', encoding='UTF-8')
ãƒ‡ãƒ¼ã‚¿_cy.DOI = ãƒ‡ãƒ¼ã‚¿_cy.DOI.str.lower()
ãƒ‡ãƒ¼ã‚¿_cy = ãƒ‡ãƒ¼ã‚¿_cy.drop_duplicates()
ãƒ‡ãƒ¼ã‚¿_cy.shape

(9249991, 2)

In [9]:
ãƒ‡ãƒ¼ã‚¿_tw_men = pd.read_csv('data/final_mentions_full_bots.tsv', sep='\t', encoding='UTF-8',
                         dtype={'Outlet or Author':str, 'External Mention ID':str})
ãƒ‡ãƒ¼ã‚¿_tw_men.DOI = ãƒ‡ãƒ¼ã‚¿_tw_men.DOI.str.lower()
ãƒ‡ãƒ¼ã‚¿_tw_men.shape

(51230936, 6)

In [15]:
ãƒ‡ãƒ¼ã‚¿_tw_men[ãƒ‡ãƒ¼ã‚¿_tw_men.DOI.isin(ãƒ‡ãƒ¼ã‚¿_cy.DOI.tolist())].shape

(51009631, 6)

In [16]:
ãƒ‡ãƒ¼ã‚¿_tw_men_cy = ãƒ‡ãƒ¼ã‚¿_tw_men.merge(ãƒ‡ãƒ¼ã‚¿_cy, how='inner', on='DOI')
ãƒ‡ãƒ¼ã‚¿_tw_men_cy.shape

(55557285, 7)

In [17]:
ãƒ‡ãƒ¼ã‚¿_tw_men_cy = bot_mentions(ãƒ‡ãƒ¼ã‚¿_tw_men_cy, agg_by='country')
ãƒ‡ãƒ¼ã‚¿_tw_men_cy = ãƒ‡ãƒ¼ã‚¿_tw_men_cy.reset_index()
ãƒ‡ãƒ¼ã‚¿_tw_men_cy

,papers_mentioned,tweeters,bots,mentions,mentions_bot,tweets,tweets_bot,retweet,retweet_bot,bots_p,bot_mentions_p,bot_tweets_p,bot_retweet_p
country,,,,,,,,,,,,,
Afghanistan,82,354,19,508,31,230,21,278,10,5.367232,6.102362,9.130435,3.597122
Albania,86,304,31,397,35,205,32,192,3,10.197368,8.816121,15.609756,1.562500
Algeria,1559,2629,256,5012,841,2963,769,2049,72,9.737543,16.779729,25.953426,3.513909
Andorra,6,89,1,96,1,30,0,66,1,1.123596,1.041667,0.000000,1.515152
Angola,31,121,13,164,19,90,18,74,1,10.743802,11.585366,20.000000,1.351351
...,...,...,...,...,...,...,...,...,...,...,...,...,...
Venezuela,622,3962,135,6383,338,2277,314,4106,24,3.407370,5.295316,13.790075,0.584510
Vietnam,4451,18972,614,30354,2595,12397,2332,17957,263,3.236348,8.549120,18.811003,1.464610
Yemen,207,408,45,728,80,418,65,310,15,11.029412,10.989011,15.550239,4.838710
Zambia,442,2243,101,3403,242,1455,189,1948,53,4.502898,7.111372,12.989691,2.720739
Zimbabwe,636,2740,102,4944,241,2014,198,2930,43,3.722628,4.874595,9.831182,1.467577

In [23]:
ãƒ‡ãƒ¼ã‚¿_tw_men_cy.sort_values(by='mentions', ascending=False).head(20)

,country,papers_mentioned,tweeters,bots,mentions,mentions_bot,tweets,tweets_bot,retweet,retweet_bot,bots_p,bot_mentions_p,bot_tweets_p,bot_retweet_p
204,United States,992381,2807476,9920,19779494,719157,6517961,562625,13261533,156532,0.353342,3.635872,8.631917,1.180346
203,United Kingdom,276466,1461463,7966,7258570,216827,2121954,165212,5136616,51615,0.545070,2.987186,7.785843,1.004844
41,China,534882,808325,6309,3126618,338385,1376440,311323,1750178,27062,0.780503,10.822716,22.617986,1.546243
73,Germany,205570,773575,6258,2856854,148695,959192,124989,1897662,23706,0.808971,5.204851,13.030655,1.249221
10,Australia,135912,613783,5221,2430035,74749,769624,58489,1660411,16260,0.850626,3.076046,7.599685,0.979276
36,Canada,137218,590827,5333,2195915,82678,742395,65758,1453520,16920,0.902633,3.765082,8.857549,1.164071
68,France,118478,509244,4732,1663406,83246,553798,69979,1109608,13267,0.929221,5.004551,12.636196,1.195647
178,Spain,126104,431533,4193,1525756,63386,512567,52483,1013189,10903,0.971652,4.154400,10.239247,1.076107
96,Japan,145806,421015,4067,1355820,95536,468040,84432,887780,11104,0.965999,7.046363,18.039484,1.250760
135,Netherlands,83475,435859,4349,1317147,52286,439361,40778,877786,11508,0.997800,3.969640,9.281206,1.311026
93,Italy,122699,380282,4237,1130882,74854,436594,64683,694288,10171,1.114173,6.619081,14.815366,1.464954
187,Switzerland,56053,351462,3887,970046,42652,315428,34400,654618,8252,1.105952,4.396905,10.905817,1.260583
186,Sweden,53670,370003,3797,930244,36844,300522,30039,629722,6805,1.026208,3.960681,9.995608,1.080636
53,Denmark,36011,295615,3125,712141,25221,232254,20127,479887,5094,1.057118,3.541574,8.665943,1.061500
92,Israel,29216,301383,2988,640332,21596,191143,17387,449189,4209,0.991430,3.372625,9.096331,0.937022
27,Brazil,76956,212089,2659,564120,44307,230744,39830,333376,4477,1.253719,7.854180,17.261554,1.342928
176,South Korea,84001,212063,3131,524895,49307,220662,44379,304233,4928,1.476448,9.393688,20.111755,1.619811
87,India,84987,181567,2599,510730,53826,226659,48008,284071,5818,1.431428,10.539032,21.180716,2.048080
18,Belgium,38683,213492,2711,493934,24111,170354,20456,323580,3655,1.269837,4.881421,12.007936,1.129551
143,Norway,27784,189460,2345,412466,16379,135257,13342,277209,3037,1.237728,3.970994,9.864184,1.095563

In [25]:
ãƒ‡ãƒ¼ã‚¿_tw_men_cy.to_csv('results/agg_bot_mentions_country.tsv', sep='\t', index=False)